spring:
  application:
    name: gemini-ai
  profiles:
    active: dev
    include: cloud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-server:3306/gemini_ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: docker-server
      port: 6379
      database: 7
      timeout: 10000
  cache:
    type: redis
    redis:
      cache-null-values: true
      key-prefix: "gemini-ai:cache:"
      time-to-live: 1000
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: llama2-chinese
      chat:
        model: llama2-chinese
gemini:
  open-api:
    enabled: true
    info:
      version: "0.0.1-SNAPSHOT"
      title: "Gemini AI Boot"
      description: "AI服务"
      contact:
        name: "Gemini AI"
        email: "gemini@glseven.com"
        url: "https://www.glseven.com"